### ISSUE TITLE
KeyError: 'followerCount'

### ISSUE THREAD

**Issue by Bobpick** [soxoj/maigret#12]
This does not happen in all of my searches, but one in particular, which I will redact, dies during searching eBay.
[+] Ebay: https://www.ebay.com/usr/fluffybutt
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "maigret/__main__.py", line 14, in <module>
    maigret.main()
  File "maigret/maigret.py", line 752, in main
    debug=args.debug)
  File "maigret/maigret.py", line 404, in sherlock
    extracted_ids_data = extract(r.text)
  File "/home/bob/.local/lib/python3.6/site-packages/socid_extractor/main.py", line 662, in extract
    value = get_field(json_data)
  File "/home/bob/.local/lib/python3.6/site-packages/socid_extractor/main.py", line 565, in <lambda>
    'follower_count': lambda x: x['person-contacts-count-models'][0]['followerCount'],
KeyError: 'followerCount'

Any suggestion how to deal with this?

**Comment by soxoj** [comment]
Hey @Bobpick, thanks for reporting. This is an error of library socid_extractor` from requirements. I suppose it was fixed [2 weeks ago](https://github.com/soxoj/socid_extractor/commit/e6c43238b2cbe2baa94fd2a2d75d755d3bd608d8), but you still use old version. Please do `pip3 install -r requirements.txt` and check once again.

**Comment by Bobpick** [comment]
I did as you suggested, and the error remains:
[+] Ebay: https://www.ebay.com/usr/fluffybunny (redacted the username - I can provide upon PM)
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "maigret/__main__.py", line 14, in <module>
    maigret.main()
  File "maigret/maigret.py", line 752, in main
    debug=args.debug)
  File "maigret/maigret.py", line 404, in sherlock
    extracted_ids_data = extract(r.text)
  File "/home/bob/.local/lib/python3.6/site-packages/socid_extractor/main.py", line 662, in extract
    value = get_field(json_data)
  File "/home/bob/.local/lib/python3.6/site-packages/socid_extractor/main.py", line 565, in <lambda>
    'follower_count': lambda x: x['person-contacts-count-models'][0]['followerCount'],
KeyError: 'followerCount'

**Comment by Greshnik83** [comment]
Что это?

сб, 26 сент. 2020 г., 15:58 Bobpick <notifications@github.com>:

**Comment by soxoj** [comment]
@Bobpick okay, PM me username, please

**Comment by Bobpick** [comment]
I don't see how to do so on Github, so I followed you on twitter, I can send you a PM there.

**Comment by soxoj** [comment]
Got the username and tested search with it, thank you. Fixed ambiguity in socid_extractor detecting rules, you must reinstall dependencies again and the problem should be solved.
`pip3 install  -r requirements.txt --upgrade --force-reinstall`

**Comment by Bobpick** [comment]
I did the above, and it threw an error. Sorry, I just upgraded my Python to 3.8.5
This is the error I now receive when trying to use that username. 

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "maigret/__main__.py", line 11, in <module>
    import maigret
  File "maigret/maigret.py", line 11, in <module>
    import aiohttp
ModuleNotFoundError: No module named 'aiohttp'

**Comment by soxoj** [comment]
Oh, I see. Update the code from repository with `git pull` or install aiohttp manually: `pip3 install aiohttp==3.5.4`

**Comment by soxoj** [comment]
@Bobpick any progress?

**Comment by Bobpick** [comment]
Yes, after I upgraded to Ubuntu 20.04 LTS, it works like a champ!

**Comment by soxoj** [comment]
Great!
